apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: dst
      image: busybox:1.36
      # 'tar' must be available in the image
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: files
          mountPath: /data
  volumes:
    - name: files
      emptyDir: {}