apiVersion: v1
kind: Pod
metadata:
  name: pod-dst
spec:
  containers:
  - name: dst
    image: busybox:1.34
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: files
      mountPath: /data
  volumes:
  - name: files
    emptyDir: {}